services:
  postgres:
    image: postgres:16-alpine
    container_name: tm-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: tm-discovery
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: tm-config
    ports:
      - "8888:8888"
    environment:
      EUREKA_URI: http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: tm-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    container_name: tm-task-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      DB_USERNAME: taskuser
      DB_PASSWORD: taskpass
      EUREKA_URI: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started

  ai-service:
    build:
      context: .
      dockerfile: ai-service/Dockerfile
    container_name: tm-ai-service
    ports:
      - "8082:8082"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      EUREKA_URI: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: tm-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api-gateway
      - task-service
      - ai-service

  grafana:
    image: grafana/grafana:11.1.0
    container_name: tm-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  pgdata:
